dist: xenial
language: cpp
os:
  - osx
  - linux
compiler:
  - clang
  - gcc
sudo: required
env:
    - CI_BUILD=cmake
    - CI_BUILD=autotools
matrix:
  exclude:
  # Exclude gcc build (Need some work) with osx
  - os: osx
    compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - autoconf
    - automake
    - autotools-dev
    - libtool
    - pkg-config
    - libcunit1-dev
    - cmake
    - cmake-data
before_install:
  - $CC --version
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then CMAKE_OPTS=" -DENABLE_ASAN=1" AUTOTOOLS_OPTS=" --enable-asan"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then  if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8" EXTRA_LDFLAGS="-fuse-ld=gold"; else export CXX="clang++" CC="clang"; fi; fi
  - $CC --version
  - cmake --version
before_script:
  # First build external lib
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install cunit; fi
  # configure nghttp3
  - if [ "$CI_BUILD" == "autotools" ]; then autoreconf -i; fi
  - if [ "$CI_BUILD" == "autotools" ]; then ./configure --enable-werror $AUTOTOOLS_OPTS; fi
  - if [ "$CI_BUILD" == "cmake" ]; then cmake $CMAKE_OPTS .; fi
script:
  # Now build nghttp3 examples and test
  - make
  - make check
